### ISSUE TITLE
[BUG] AniWorld streaming

### ISSUE THREAD

**Issue by SyrHamza** [cranci1/Ryu#32]
**Describe the bug**
On AniWorld when i want to Watch a Video it says ERROR with the error Code : Error extracting source URL 

**To Reproduce**
1) OPEN RYU App Then Click on Anime then on an Episode but then it gives me Error 

**Expected behavior**
I expected to load the Episode and Open the Video 

**Screenshots**
I have for example in One piece but its on all the Same

**Device (please complete the following information):**
 - Device: iPad Air 5
 - OS: [e.g. iPadOS 17.7.1
 - Version [.  2.   ]

**Additional context**
Its only on AniWorld the other Ones working  Fine but I Need the german One thanks
![IMG_0103](https://github.com/user-attachments/assets/c1548d82-ff4c-4b1b-90b2-8e4e7672b15a)

**Comment by cranci1** [comment]
Very very weird, can you try sending me a image of you using the "Play in Browser" feature? Because is very weird, for some reasons to all people that need aniworld as source it doesn't work

**Comment by cranci1** [comment]
@SyrHamza can you try to use a VPN like cloudflare warp? This should fix the issue 99%

AppStore: https://apps.apple.com/us/app/1-1-1-1-faster-internet/id1423538627

**Comment by SyrHamza** [comment]
![Screenshot_20241206_163357_CloudStream](https://github.com/user-attachments/assets/f5b4958b-4dcd-498e-9008-755dfc759f71)

So i tried what u say but it doesnt help, in the notification line u can see i use 1111 vpn but it Shows still the same. I also tried to watch different animies but it dont work.  Holen u can fix it :) 
And thank u

**Comment by cranci1** [comment]
The thing is that the app in the photo is not Ryu, its a different app since Ryu doesn't support android

**Comment by SyrHamza** [comment]
Oh sry i were thinking u mean another Thing, im will try it now

**Comment by SyrHamza** [comment]
![IMG_0108](https://github.com/user-attachments/assets/50267539-6794-4c03-a41a-3f83c21fd6f3)

So… Here I have the ryu App with the vpn activated and still the Same Error .
Sry fit the other Photo I also have the Same Problem with cloudstream

**Comment by cranci1** [comment]
Yeah the issue is probably related. Users that live in Germany have reported me that AniWorld doesn't work too.

**Comment by SyrHamza** [comment]
So we have to wait?

**Comment by cranci1** [comment]
Yeah im wait for a Ryu user to tell me which VPN he uses to fix AniWorld

**Comment by SyrHamza** [comment]
Ok

**Comment by cranci1** [comment]
Ok so the guy responded, he's using "Hotspotshield free version", you can download it here: https://apps.apple.com/us/app/super-vpn-hotspot-shield-proxy/id443369807

It's likely to also fix the cloudstream issue too

**Comment by SyrHamza** [comment]
So it Works at First but Then it didnt found any Videos 
![IMG_0109](https://github.com/user-attachments/assets/fa1cfbe0-eb8d-47c6-bde9-fd4669366d8b)

**Comment by SyrHamza** [comment]
But its not always so

**Comment by SyrHamza** [comment]
Hello cranci, at First i want to 
Trank u that its work 50% . But the bug is that it Cent find any Videos sehen we looking for it, u only can Watch when u set the Anime to favorite but to do that u have to load the Videos which doesnt work. :(  the Same Photo as before

**Comment by cranci1** [comment]
Thanks, I'm still looking in to the issue and try to see if i can fix something
